extends SceneTree
func _init() -> void:
    var packed: PackedScene = load("res://scenes/main.tscn")
    var scene: Variant = packed.instantiate()
    root.add_child(scene)
    await process_frame
    assert(ResourceLoader.exists("res://assets/art/game_icon.png"))
    assert(ResourceLoader.exists("res://assets/art/items/acorn_strip.png"))
    assert(ResourceLoader.exists("res://assets/art/items/pinecone_strip.png"))
    assert(ResourceLoader.exists("res://assets/art/items/seasonal_hazards.png"))
    scene._start_level(1)
    assert(scene.screen == "play")
    assert(scene.SQUIRREL_BASE_SCALE > 0.44)
    assert(is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y))
    assert(is_equal_approx(scene.GROUND_LINE_Y - scene.squirrel.position.y, scene.SQUIRREL_FOOT_OFFSET))
    assert(scene.squirrel.sprite_frames.has_animation("idle"))
    assert(scene.squirrel.sprite_frames.has_animation("run_left"))
    assert(scene.squirrel.sprite_frames.has_animation("run_right"))
    assert(scene.squirrel.sprite_frames.has_animation("flatten"))
    assert(scene.squirrel.sprite_frames.has_animation("pop"))
    var idle_frame: AtlasTexture = scene.squirrel.sprite_frames.get_frame_texture("idle", 0)
    assert(idle_frame.region.position.y < scene.sheet.get_height() * 2 / 3)
    scene._update_play(0.2)
    assert(not is_equal_approx(scene.squirrel.scale.x, scene.SQUIRREL_BASE_SCALE))
    assert(not is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y))
    scene._set_lane(4)
    scene._update_play(0.01)
    assert(scene.player_lane == 4 and scene.squirrel.animation == "run_right")
    assert(is_equal_approx(scene.squirrel.scale.x, scene.SQUIRREL_BASE_SCALE))
    assert(is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y) and is_zero_approx(scene.squirrel.rotation))
    scene._start_level(1)
    var blocked_lane: int = (scene.player_lane + 2) % 5
    scene.drops = [{"kind": "acorn", "lane": blocked_lane, "y": -120.0, "speed": scene.definition.base_speed}]
    assert(scene._replacement_lane() != blocked_lane)
    scene.drops.clear()
    scene._start_level(5)
    assert(scene.definition.theme.family == "pinecone" and scene.item_textures.pinecone != null)
    scene._start_level(9)
    assert(scene.definition.theme.minor == "snowflake" and scene.definition.theme.major == "icicle" and scene.hazard_texture != null)
    assert(scene._map_node_position(1).y > scene._map_node_position(10).y)
    assert(scene._map_node_position(1).x != scene._map_node_position(2).x)
    assert(scene._map_node_position(10).y >= 330.0)
    scene.screen = "map"
    scene._process(0.0)
    assert(not scene.squirrel.visible)
    scene.screen = "settings"
    scene._process(0.0)
    assert(not scene.squirrel.visible)
    scene._start_level(1)
    scene._process(0.0)
    assert(scene.squirrel.visible)
    scene._limb_hit({})
    assert(scene.screen == "recover" and scene.recover_phase == 0)
    assert(is_equal_approx(scene.squirrel.scale.x, scene.SQUIRREL_BASE_SCALE))
    assert(is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y) and is_zero_approx(scene.squirrel.rotation))
    scene.squirrel.frame = scene.squirrel.sprite_frames.get_frame_count("flatten") - 1
    scene._update_recovery(0.0)
    assert(scene.recover_phase == 1 and scene.squirrel.animation == "flatten")
    scene._update_recovery(scene.FLATTEN_HOLD_SECONDS - 0.01)
    assert(scene.recover_phase == 1 and scene.squirrel.animation == "flatten")
    scene._update_recovery(0.02)
    assert(scene.recover_phase == 2 and scene.squirrel.animation == "pop")
    scene.paused = true
    assert(scene.paused)
    scene._pause_click(Vector2(300, 850))
    assert(not scene.paused)
    var original_music: bool = scene.save_data.music
    scene.screen = "settings"
    scene._settings_click(Vector2(300, 650))
    assert(scene.save_data.music != original_music)
    scene._settings_click(Vector2(10, 10))
    assert(scene.screen == "map")
    scene._start_level(1)
    scene.logic.progress = scene.logic.recipe.size()
    scene._finish_level()
    assert(int(scene.save_data.unlocked) >= 2)
    for n in range(1,11):
        scene._start_level(n)
        assert(scene.logic.recipe.size() == (3 if n <= 3 else 4 if n <= 7 else 5))
    print("RUNTIME_SMOKE_PASS")
    quit()
