extends SceneTree
func _init() -> void:
    var packed: PackedScene = load("res://scenes/main.tscn")
    var scene: Variant = packed.instantiate()
    root.add_child(scene)
    await process_frame
    assert(ResourceLoader.exists("res://assets/art/game_icon.png"))
    assert(ResourceLoader.exists("res://assets/art/nuts_boot_splash.png"))
    assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_2.png"))
    assert(ResourceLoader.exists("res://assets/art/squirrel_sheet_packed.png"))
    assert(ResourceLoader.exists("res://assets/art/items/acorn_strip.png"))
    assert(ResourceLoader.exists("res://assets/art/items/pinecone_strip.png"))
    assert(ResourceLoader.exists("res://assets/art/items/seasonal_hazards.png"))
    assert(ResourceLoader.exists("res://assets/art/items/branch_clean_v1.png"))
    scene.screen = "title"
    var title_tap := InputEventScreenTouch.new()
    title_tap.pressed = true
    title_tap.position = Vector2(540.0, 960.0)
    scene._unhandled_input(title_tap)
    assert(scene.screen == "map")
    var level_one_click := InputEventMouseButton.new()
    level_one_click.button_index = MOUSE_BUTTON_LEFT
    level_one_click.pressed = true
    level_one_click.position = scene._map_node_position(1)
    scene._unhandled_input(level_one_click)
    assert(scene.screen == "play" and scene.level_number == 1)
    assert(scene.screen == "play")
    assert(ProjectSettings.get_setting("application/boot_splash/image") == "res://assets/art/nuts_boot_splash.png")
    assert(ProjectSettings.get_setting("application/boot_splash/show_image") == true)
    assert(ProjectSettings.get_setting("application/boot_splash/stretch_mode") == 1)
    assert(scene.TITLE_CTA == "TAP TO PLAY" and scene.TITLE_CTA != "TAP TO CLIMB")
    assert(scene.SQUIRREL_BASE_SCALE > 0.44)
    assert(is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y))
    assert(is_equal_approx(scene.GROUND_LINE_Y - scene.squirrel.position.y, scene.SQUIRREL_FOOT_OFFSET))
    assert(scene.squirrel.sprite_frames.has_animation("idle"))
    assert(scene.squirrel.sprite_frames.has_animation("run_left"))
    assert(scene.squirrel.sprite_frames.has_animation("run_right"))
    assert(scene.squirrel.sprite_frames.has_animation("flatten"))
    assert(scene.squirrel.sprite_frames.has_animation("pop"))
    var idle_frame: AtlasTexture = scene.squirrel.sprite_frames.get_frame_texture("idle", 0)
    assert(scene.sheet.get_width() == 2048 and scene.sheet.get_height() == 1536)
    assert(idle_frame.region.size == Vector2(512, 512))
    assert(idle_frame.region.position == Vector2(0, 1024))
    scene._update_play(0.2)
    assert(not is_equal_approx(scene.squirrel.scale.x, scene.SQUIRREL_BASE_SCALE))
    assert(not is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y))
    scene._set_lane(4)
    scene._update_play(0.01)
    assert(scene.player_lane == 4 and scene.squirrel.animation == "run_right")
    assert(is_equal_approx(scene.squirrel.scale.x, scene.SQUIRREL_BASE_SCALE))
    assert(is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y) and is_zero_approx(scene.squirrel.rotation))
    scene._start_level(1)
    var mouse_press := InputEventMouseButton.new()
    mouse_press.button_index = MOUSE_BUTTON_LEFT
    mouse_press.pressed = true
    mouse_press.position = Vector2(scene.LANE_X[0], 1200.0)
    scene._unhandled_input(mouse_press)
    assert(scene.player_lane == 0)
    var mouse_motion := InputEventMouseMotion.new()
    mouse_motion.position = Vector2(scene.LANE_X[4], 1200.0)
    scene._unhandled_input(mouse_motion)
    assert(scene.player_lane == 4 and scene.player_target_x == scene.LANE_X[4])
    var mouse_release := InputEventMouseButton.new()
    mouse_release.button_index = MOUSE_BUTTON_LEFT
    mouse_release.pressed = false
    mouse_release.position = Vector2(scene.LANE_X[4], 1200.0)
    scene._unhandled_input(mouse_release)
    var screen_drag := InputEventScreenDrag.new()
    screen_drag.position = Vector2(scene.LANE_X[1], 1200.0)
    scene._unhandled_input(screen_drag)
    assert(scene.player_lane == 1 and scene.player_target_x == scene.LANE_X[1])
    scene._start_level(1)
    var blocked_lane: int = (scene.player_lane + 2) % 5
    scene.drops = [{"kind": "acorn", "lane": blocked_lane, "y": -120.0, "speed": scene.definition.base_speed}]
    assert(scene._replacement_lane() != blocked_lane)
    scene.drops.clear()
    scene._start_level(5)
    assert(scene.definition.theme.family == "pinecone" and scene.item_textures.pinecone != null and scene.branch_texture != null)
    assert(scene._hazard_texture_for("stick") == scene.branch_texture and scene._hazard_texture_for("branch") == scene.branch_texture)
    scene._start_level(9)
    assert(scene.definition.theme.minor == "snowflake" and scene.definition.theme.major == "icicle" and scene.hazard_texture != null)
    assert(scene._map_node_position(1).y > scene._map_node_position(10).y)
    assert(scene._map_node_position(1).x != scene._map_node_position(2).x)
    assert(scene._map_node_position(10).y >= 420.0)
    assert(scene._map_node_position(10).y > 400.0 and scene._map_node_position(1).y < 1700.0)
    scene.screen = "map"
    scene._process(0.0)
    assert(not scene.squirrel.visible)
    assert(scene.map_page == 1)
    scene.save_data.unlocked = 20
    scene._map_click(Vector2(950, 240))
    assert(scene.crossing_time > 0.0)
    scene._update_map_crossing(0.01)
    assert(scene.squirrel.visible)
    scene._update_map_crossing(0.61)
    assert(scene.map_page == 2 and scene._map_node_position(11).y > scene._map_node_position(20).y)
    scene.screen = "settings"
    scene._process(0.0)
    assert(not scene.squirrel.visible)
    scene._start_level(1)
    scene._process(0.0)
    assert(scene.squirrel.visible)
    scene.logic.progress = 2
    scene._update_carry_stack()
    assert(scene.carry_sprites[0].visible and scene.carry_sprites[1].visible)
    assert(scene.carry_sprites[0].position.y < scene.SQUIRREL_Y - 50.0 and scene.carry_sprites[0].position.x > scene.player_x + 20.0)
    assert(scene.carry_sprites[0].z_index > scene.squirrel.z_index)
    scene._set_lane(4)
    scene.player_x = scene.LANE_X[4]
    scene._update_carry_stack()
    assert(scene.carry_sprites[0].position.x < scene.player_x and scene.carry_sprites[0].position.x < scene.PLAY_RIGHT)
    scene._limb_hit({})
    assert(scene.screen == "recover" and scene.recover_phase == 0)
    assert(is_equal_approx(scene.squirrel.scale.x, scene.SQUIRREL_BASE_SCALE))
    assert(is_equal_approx(scene.squirrel.position.y, scene.SQUIRREL_Y) and is_zero_approx(scene.squirrel.rotation))
    scene.squirrel.frame = scene.squirrel.sprite_frames.get_frame_count("flatten") - 1
    scene._update_recovery(0.0)
    assert(scene.recover_phase == 1 and scene.squirrel.animation == "flatten")
    scene._update_recovery(scene.FLATTEN_HOLD_SECONDS - 0.01)
    assert(scene.recover_phase == 1 and scene.squirrel.animation == "flatten")
    scene._update_recovery(0.02)
    assert(scene.recover_phase == 2 and scene.squirrel.animation == "pop")
    scene.paused = true
    assert(scene.paused)
    scene._pause_click(Vector2(300, 850))
    assert(not scene.paused)
    var original_music: bool = scene.save_data.music
    scene.screen = "settings"
    scene._settings_click(Vector2(300, 650))
    assert(scene.save_data.music != original_music)
    scene._settings_click(Vector2(10, 10))
    assert(scene.screen == "map")
    scene._start_level(1)
    scene.logic.progress = scene.logic.recipe.size()
    scene._finish_level()
    assert(int(scene.save_data.unlocked) >= 2)
    for n in range(1,21):
        scene._start_level(n)
        assert(scene.logic.recipe.size() == (3 if n <= 3 else 4 if n <= 7 else 5))
    scene._start_level(99)
    assert(scene.level_number == 20 and scene.definition.number == 20)
    scene.screen = "title"
    scene._process(0.0)
    assert(scene.squirrel.visible and scene.squirrel.position.y > 1200.0 and scene.squirrel.scale.x >= 0.65)
    scene.screen = "results"
    scene._process(0.0)
    assert(scene.squirrel.visible and scene.squirrel.position.y > 1200.0)
    print("RUNTIME_SMOKE_PASS")
    quit()
