extends SceneTree

const AdMobProjectSettings = preload("res://addons/admob/internal/services/project_settings_service.gd")

func _init() -> void:
	var config := ConfigFile.new()
	assert(config.load("res://export_presets.cfg") == OK)
	var exclusions := str(config.get_value("preset.0", "exclude_filter", ""))
	assert(exclusions.contains("build/**") and exclusions.contains("addons/admob/gdscript/sample/**"))
	assert(config.get_value("preset.0.options", "gradle_build/use_gradle_build", false))
	assert(config.get_value("preset.0.options", "permissions/internet", false))
	assert(config.get_value("preset.0.options", "permissions/access_network_state", false))
	assert(config.get_value("preset.0.options", "version/code", 0) == 23)
	assert(config.get_value("preset.0.options", "version/name", "") == "1.0.22")
	assert(config.get_value("preset.0.options", "launcher_icons/main_192x192", "") == "res://assets/art/game_icon.png")
	# Both packages stay in the com.grapegames namespace; debug is suffixed so a
	# sideloaded build installs alongside the Play build instead of replacing it.
	assert(config.get_value("preset.0.options", "package/unique_name", "") == "com.grapegames.nuts.debug")
	assert(config.get_value("preset.1", "name", "") == "Android Play")
	assert(config.get_value("preset.1.options", "gradle_build/export_format", 0) == 1)
	assert(config.get_value("preset.1.options", "package/unique_name", "") == "com.grapegames.nuts")
	assert(config.get_value("preset.1.options", "permissions/internet", false))
	assert(config.get_value("preset.1.options", "permissions/access_network_state", false))
	var project := ConfigFile.new()
	assert(project.load("res://project.godot") == OK)
	assert(project.get_value("application", "config/icon", "") == "res://assets/art/game_icon.png")
	assert(project.get_value("autoload", "AdBarService", "") == "*res://autoload/ad_bar_service.gd")
	assert(project.get_value("editor_plugins", "enabled", PackedStringArray()).has("res://addons/admob/plugin.cfg"))
	assert(project.get_value("admob", "general/android/enabled", true))
	assert(project.get_value("admob", "general/android/app_id", AdMobProjectSettings.ANDROID_DEFAULT_APP_ID) == AdMobProjectSettings.ANDROID_DEFAULT_APP_ID)
	assert(AdMobProjectSettings.ANDROID_DEFAULT_APP_ID == "ca-app-pub-3940256099942544~3347511713")
	assert(not project.get_value("admob", "general/ios/enabled", true))
	assert(FileAccess.file_exists("res://addons/admob/plugin.cfg"))
	assert(ResourceLoader.exists("res://autoload/ad_bar_service.gd"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v2.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v3.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v4.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v5.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/high_canopy_day_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/high_canopy_night_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/high_canopy_storm_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/play_limb_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/play_limb_day_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/hawk_swoop_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/owl_swoop_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/lightning_fx_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/firefly_swarm_v1.png"))
	print("EXPORT_CONFIG_TEST_PASS")
	quit()
