extends SceneTree


func _init() -> void:
	var config := ConfigFile.new()
	assert(config.load("res://export_presets.cfg") == OK)
	assert(config.get_value("preset.0", "exclude_filter", "") == "build/**")
	assert(config.get_value("preset.0.options", "version/code", 0) == 19)
	assert(config.get_value("preset.0.options", "version/name", "") == "1.0.18")
	assert(config.get_value("preset.0.options", "launcher_icons/main_192x192", "") == "res://assets/art/game_icon.png")
	var project := ConfigFile.new()
	assert(project.load("res://project.godot") == OK)
	assert(project.get_value("application", "config/icon", "") == "res://assets/art/game_icon.png")
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v2.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v3.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v4.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/tree_trail_real_v5.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/high_canopy_day_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/high_canopy_night_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/seasonal/high_canopy_storm_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/play_limb_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/hawk_swoop_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/owl_swoop_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/lightning_fx_v1.png"))
	assert(ResourceLoader.exists("res://assets/art/canopy/firefly_swarm_v1.png"))
	print("EXPORT_CONFIG_TEST_PASS")
	quit()
